name: Scheduled Blog Posts

on:
  schedule:
    # Runs at 10:00 AM on Monday and Thursday
    - cron: '0 10 * * 1,4'
  workflow_dispatch: # Allows manual triggering

jobs:
  blog-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Add job to blog queue
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"secret":"${{ secrets.BLOG_GENERATOR_SECRET }}"}' \
          https://vibebeachhouse.vercel.app/api/generate-blog
      
      # Add a pause to allow queue update to propagate  
      - name: Wait for queue update
        run: sleep 30
      
      - name: Process next job in queue
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"secret":"${{ secrets.BLOG_GENERATOR_SECRET }}"}' \
          https://vibebeachhouse.vercel.app/api/process-blog-queue