name: Scheduled Blog Posts

on:
  schedule:
    # Runs at 10:00 AM on Monday and Thursday
    - cron: '0 10 * * 1,4'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write  # Give write permissions to repository contents
  
jobs:
  blog-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install openai fs path
      
      - name: Generate Fort Lauderdale surf blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/generate-local-blog.mjs
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit and push blog post
        run: |
          git add posts/
          git commit -m "Add automated blog post for Vibe Surf School" || echo "No changes to commit"
          git push
      
      - name: Completion message
        run: echo "Blog post generation and publishing completed"